kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "accountpooloperator-role"
rules:
- apiGroups: ["accountpooloperator.openshift.io"] 
  resources: ["awsaccounts"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
- apiGroups: ["accountpooloperator.openshift.io"]
  resources: ["accountpools"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]