/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	accountpooloperatorv1 "gitlab.cee.redhat.com/service/uhc-clusters-service/pkg/accountpooloperator/pkg/apis/accountpooloperator/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAccountPools implements AccountPoolInterface
type FakeAccountPools struct {
	Fake *FakeAccountpooloperatorV1
	ns   string
}

var accountpoolsResource = schema.GroupVersionResource{Group: "accountpooloperator.openshift.io", Version: "v1", Resource: "accountpools"}

var accountpoolsKind = schema.GroupVersionKind{Group: "accountpooloperator.openshift.io", Version: "v1", Kind: "AccountPool"}

// Get takes name of the accountPool, and returns the corresponding accountPool object, and an error if there is any.
func (c *FakeAccountPools) Get(name string, options v1.GetOptions) (result *accountpooloperatorv1.AccountPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(accountpoolsResource, c.ns, name), &accountpooloperatorv1.AccountPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*accountpooloperatorv1.AccountPool), err
}

// List takes label and field selectors, and returns the list of AccountPools that match those selectors.
func (c *FakeAccountPools) List(opts v1.ListOptions) (result *accountpooloperatorv1.AccountPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(accountpoolsResource, accountpoolsKind, c.ns, opts), &accountpooloperatorv1.AccountPoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &accountpooloperatorv1.AccountPoolList{ListMeta: obj.(*accountpooloperatorv1.AccountPoolList).ListMeta}
	for _, item := range obj.(*accountpooloperatorv1.AccountPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested accountPools.
func (c *FakeAccountPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(accountpoolsResource, c.ns, opts))

}

// Create takes the representation of a accountPool and creates it.  Returns the server's representation of the accountPool, and an error, if there is any.
func (c *FakeAccountPools) Create(accountPool *accountpooloperatorv1.AccountPool) (result *accountpooloperatorv1.AccountPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(accountpoolsResource, c.ns, accountPool), &accountpooloperatorv1.AccountPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*accountpooloperatorv1.AccountPool), err
}

// Update takes the representation of a accountPool and updates it. Returns the server's representation of the accountPool, and an error, if there is any.
func (c *FakeAccountPools) Update(accountPool *accountpooloperatorv1.AccountPool) (result *accountpooloperatorv1.AccountPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(accountpoolsResource, c.ns, accountPool), &accountpooloperatorv1.AccountPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*accountpooloperatorv1.AccountPool), err
}

// Delete takes name of the accountPool and deletes it. Returns an error if one occurs.
func (c *FakeAccountPools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(accountpoolsResource, c.ns, name), &accountpooloperatorv1.AccountPool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAccountPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(accountpoolsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &accountpooloperatorv1.AccountPoolList{})
	return err
}

// Patch applies the patch and returns the patched accountPool.
func (c *FakeAccountPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *accountpooloperatorv1.AccountPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(accountpoolsResource, c.ns, name, data, subresources...), &accountpooloperatorv1.AccountPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*accountpooloperatorv1.AccountPool), err
}
