apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "accountpools.accountpooloperator.openshift.io"
spec:
  group: "accountpooloperator.openshift.io"
  version: "v1"
  scope: "Namespaced"
  names:
    plural: "accountpools"
    singular: "accountpool"
    kind: "AccountPool"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["provider", "credentials", "pool_size"]
          properties:
            provider:
              type: "string"
            credentials:
              type: "object"
            pool_size:
              type: "integer"
              minimum: 1