apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "awsaccounts.accountpooloperator.openshift.io"
spec:
  group: "accountpooloperator.openshift.io"
  version: "v1"
  scope: "Namespaced"
  names:
    plural: "awsaccounts"
    singular: "awsaccount"
    kind: "AWSAccount"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["account_name", "email", "status"]
          properties:
            account_name:
              type: "string"
            email:
              type: "string"
            status:
              type: "string"